App-wed/App-wed/Models/EntradasModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace App_wed.Models
{
    public class EntradasModel
    {
        public int Id { get; set; }
        public string Descricion { get; set; }
    }
}

App-wed/App-wed/Models/EstadioModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace App_wed.Models
{
    public class EstadioModel
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
    }
}

App-wed/App-wed/Models/MyEquipoModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace App_wed.Models
{
    public class MyEquipoModel
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
    }
}

App-wed/App-wed/Models/ProductoModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace App_wed.Models
{
    public class ProductoModel
    {
        public int Id { get; set; }
        public string Descripcion{ get; set; }

    }
}

App-wed/App-wed/Models/TiendaModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace App_wed.Models
{
    public class TiendaModel
    {
        public int Id { get; set; }

        public string Descripcion { get; set; }
    }
}

App-wed/App-wed/Controllers/EntradasController.cs
using App_wed.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace App_wed.Controllers
{
    public class EntradasController : Controller
    {
        // GET: Entradas
        public ActionResult Index()
        {
            var entrada1 = new EntradasModel();
            entrada1.Id = 1;
            entrada1.Descricion = "VIP";

            var entrada2 = new EntradasModel();
            entrada2.Id = 1;
            entrada2.Descricion = "Palco";

            var entrada3 = new EntradasModel();
            entrada3.Id = 1;
            entrada3.Descricion = "Silla";

            var listadeEntradas = new List<EntradasModel>();
            listadeEntradas.Add(entrada1);
            listadeEntradas.Add(entrada2);
            listadeEntradas.Add(entrada3);

            return View(listadeEntradas);
        }
    }
}

App-wed/App-wed/Controllers/EstadioController.cs
using App_wed.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace App_wed.Controllers
{
    public class EstadioController : Controller
    {
        // GET: Estadio
        public ActionResult Index()
        {
            var estadio = new EstadioModel();
            estadio.Id = 1;
            estadio.Descripcion = "Tour del Estadio";


            return View(estadio);
        }
    }
}

App-wed/App-wed/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace App_wed.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

App-wed/App-wed/Controllers/MyEquipoController.cs
using App_wed.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace App_wed.Controllers
{
    public class MyEquipoController : Controller
    {
        // GET: MyEquipo
        public ActionResult Index()
        {
            var myequipo = new MyEquipoModel();
            myequipo.Id = 1;
            myequipo.Descripcion = "Plantilla";

            return View(myequipo);
        }
    }
}

App-wed/App-wed/Controllers/ProductoController.cs
using App_wed.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace App_wed.Controllers
{
    public class ProductoController : Controller
    {
        // GET: Producto
        public ActionResult Index()
        {
            var producto1 = new ProductoModel();
            producto1.Id = 1;
            producto1.Descripcion = "Entradas";

            var producto2 = new ProductoModel();
            producto2.Id = 2;
            producto2.Descripcion = "Área VIP";

            var producto3 = new ProductoModel();
            producto3.Id = 3;
            producto3.Descripcion = "Tienda";

            var producto4 = new ProductoModel();
            producto4.Id = 4;
            producto4.Descripcion = "Fans";

            var producto5 = new ProductoModel();
            producto5.Id = 5;
            producto5.Descripcion = "Estadio";

            var producto6 = new ProductoModel();
            producto6.Id = 6;
            producto6.Descripcion = "Noticias";

            var listadeProductos = new List<ProductoModel>();
            listadeProductos.Add(producto1);
            listadeProductos.Add(producto2);
            listadeProductos.Add(producto3);
            listadeProductos.Add(producto4);
            listadeProductos.Add(producto5);
            listadeProductos.Add(producto6);

            return View(listadeProductos);
        }
    }
}

App-wed/App-wed/Controllers/TiendaController.cs
using App_wed.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace App_wed.Controllers
{
    public class TiendaController : Controller
    {
        // GET: Tienda
        public ActionResult Index()
        {
            var tienda1 = new TiendaModel();
            tienda1.Id = 1;
            tienda1.Descripcion = "Hombre";

            var tienda2 = new TiendaModel();
            tienda2.Id = 2;
            tienda2.Descripcion = "Mujer";

            var tienda3 = new TiendaModel();
            tienda3.Id = 3;
            tienda3.Descripcion = "Niño";

            var tienda4 = new TiendaModel();
            tienda4.Id = 4;
            tienda4.Descripcion = "Niña";

            var tienda5 = new TiendaModel();
            tienda5.Id = 5;
            tienda5.Descripcion = "Tarjetas de Regalo";

            var listadelaTienda = new List<TiendaModel>();
            listadelaTienda.Add(tienda1);
            listadelaTienda.Add(tienda2);
            listadelaTienda.Add(tienda3);
            listadelaTienda.Add(tienda4);
            listadelaTienda.Add(tienda5);

            return View(listadelaTienda);
        }
    }
}

App-wed/App-wed/Views/Entradas/Index.cshtml
@model List<App_wed.Models.EntradasModel>
@{
    ViewBag.Title = "Index";
}

<h2>Entradas</h2>


@foreach (var Entradas in Model)
{
    <p>@Entradas.Descricion</p>
}



App-wed/App-wed/Views/Estadio/Index.cshtml
@model App_wed.Models.EstadioModel
@{
    ViewBag.Title = "Index";
}

<h2>Estadio</h2>

<p>@Model.Descripcion</p>


App-wed/App-wed/Views/Home/Index.cshtml

@{
    ViewBag.Title = "Index";
}

<h2>Bienvenidos a Nación Deportiva</h2>


App-wed/App-wed/Views/MyEquipo/Index.cshtml
@model App_wed.Models.MyEquipoModel
@{
    ViewBag.Title = "Index";
}

<h2>MyEquipo</h2>

<p>@Model.Descripcion</p>


App-wed/App-wed/Views/Producto/Index.cshtml
@model List<App_wed.Models.ProductoModel>
@{
    ViewBag.Title = "Index";
}

<h2>Productos</h2>

@foreach (var producto in Model)
{
    <p>@producto.Id @producto.Descripcion</p>
}


App-wed/App-wed/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nación Deportiva", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Inicio", "Index", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("LISTA DE PRODUCTOS","Index", "Producto") 
                    </li>
                    <li>
                        @Html.ActionLink("TIENDA", "Index", "Tienda")
                    </li>
                    <li>
                        @Html.ActionLink("ENTRADAS", "Index", "Entradas")
                    </li>
                    <li>
                        @Html.ActionLink("MY EQUIPO", "Index", "MyEquipo")
                    </li>
                    <li>
                        @Html.ActionLink("ESTADIO", "Index", "Estadio")
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Derechos Reservados</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

App-wed/App-wed/Views/Tienda/Index.cshtml
@model List<App_wed.Models.TiendaModel>
@{
    ViewBag.Title = "Index";
}

<h2>Tienda</h2>

@foreach (var Tienda in Model)
{
    <p>@Tienda.Descripcion</p>
}